name: cicd

on: 
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch:


jobs: 
  build: 
    runs-on: ubuntu-latest 
    
    
    steps: 
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
            components: clippy, rustfmt
            override: true

      - name: Run rustfmt
        run: make format

      - name: Run clippy
        run: make lint

      - name: Run clippy
        run: make test

      - name: Run clippy
        run: make release
